services:
  api:
    build:
      context: api
#      target: builder
    container_name: fastapi-application
    volumes:
      - './api:/app'
    ports:
      - '${API_PORT}:8000'
    restart: "no"
    depends_on:
      - "pgsql"
    links:
      - "pgsql:${DB_HOST}"
  pgsql:
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE}"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres: { }