services:
  api:
    build:
      context: api
#      target: builder
    container_name: fastapi-application
    environment:
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
    volumes:
      - './api:/app'
    ports:
      - '${API_PORT}:8000'
    restart: "no"
    depends_on:
      - "pgsql"
    links:
      - "pgsql:${DB_HOST}"
  pgsql:
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE}"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
  web:
    build:
      context: app
    volumes:
      -   "./app:/app"
    environment:
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_HOST=${DB_HOST}"
      - "DB_CONNECTION=pgsql"
      - "DB_PORT=${DB_PORT}"
    ports:
      - "80:80"
      - "2222:22"
      - "4000:4000"
    depends_on:
      -   "pgsql"
    links:
      -   "pgsql:${DB_HOST}"


volumes:
  postgres: { }