services:
  api:
    build:
      context: api
#      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    volumes:
      - './api:/app'
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - "pgsql"
    links:
      - "pgsql:${DB_HOST}"
  pgsql:
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE}"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
  ide:
    build:
      context: .
    container_name: ide
    volumes:
      - '/dev/shm:/dev/shm'
      - './:/code'
      - '/run/user/0/docker.sock:/run/user/0/docker.sock'
    ports:
      - 6080:80
    links:
      - "pgsql:${DB_HOST}"
      - "api:api"
    restart: "no"


volumes:
  postgres: { }